import { Inter } from "next/font/google";
import "../globals.css";
import { dir } from 'i18next'
import { languages } from '../i18n/settings.js'
import { Navbar } from "./Components/Navbar/navbar";
import '@fortawesome/fontawesome-free/css/all.min.css'
import 'bootstrap/dist/css/bootstrap.min.css'
import { Footer } from "./Components/Footer/Footer";
import ScrolltoTop from "./Home/ScrolltoTop";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Makdouz",
  description: "Generated by Makdouz developmer team.",
};

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }))
}

export default function RootLayout({ children, params: {
  lng
} }) {
  return (

    <html lang={lng} dir={dir(lng)}>
      <body className={inter.className}>
        <Navbar lng={lng} />
        {children}
        <Footer lng={lng} />
      <ScrolltoTop />

      </body>

    </html>
  );
}
